version: "3.9"

services:
  bbw-mariadb-dev:
    image: mariadb:latest
    container_name: bbw-mariadb-dev
    environment:
      - MYSQL_ROOT_PASSWORD=bbw123
      - MYSQL_DATABASE=demo
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  bbw-phpmyadmin:
    depends_on:
      - bbw-mariadb-dev
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    environment:
      - PMA_HOST=bbw-mariadb-dev