server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: root
    password: bbw123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
