name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 3306:3306
          - 81:80
          - 3000:3000
          - 8080:8080

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push tripsfrontend image
      run: |
        docker build ./tripsfrontend --tag ${{ secrets.DOCKER_USERNAME }}/tripsfrontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tripsfrontend:latest

    - name: Build and push tripsbackend image
      run: |
        docker build ./tripsbackend --tag ${{ secrets.DOCKER_USERNAME }}/tripsbackend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tr
