name: No-Op Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  no-op:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: echo "Setting up environment"

    - name: Run no-op step
      run: echo "This is a no-op step that does nothing"

    - name: Complete
      run: echo "Workflow complete. Everything is fine!"
